// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoFinal2.Models;

namespace ProjetoFinal2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220123003737_projeto")]
    partial class projeto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoFinal2.Models.Atuacao", b =>
                {
                    b.Property<int>("Id_Atuacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Atuacao");

                    b.ToTable("Atuacao");
                });

            modelBuilder.Entity("ProjetoFinal2.Models.CadastroJuridico", b =>
                {
                    b.Property<int>("Id_Juridico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.Property<bool>("Whatsapp")
                        .HasColumnType("bit");

                    b.HasKey("Id_Juridico");

                    b.ToTable("CadastroJuridico");
                });

            modelBuilder.Entity("ProjetoFinal2.Models.CadastroPessoaGeral", b =>
                {
                    b.Property<int>("Id_Geral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assunto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensagem")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id_Geral");

                    b.ToTable("CadastroPessoaG");
                });

            modelBuilder.Entity("ProjetoFinal2.Models.CadastroPsicologoGeral", b =>
                {
                    b.Property<int>("Id_PsicoG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.Property<bool>("Whatsapp")
                        .HasColumnType("bit");

                    b.HasKey("Id_PsicoG");

                    b.ToTable("CadastroPsicologoG");
                });

            modelBuilder.Entity("ProjetoFinal2.Models.CadastroPsicologoUrgente", b =>
                {
                    b.Property<int>("Id_PsicoU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.Property<bool>("Whatsapp")
                        .HasColumnType("bit");

                    b.HasKey("Id_PsicoU");

                    b.ToTable("CadastroPsicologoU");
                });

            modelBuilder.Entity("ProjetoFinal2.Models.CadastroVagas", b =>
                {
                    b.Property<int>("Id_Vagas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.Property<bool>("Whatsapp")
                        .HasColumnType("bit");

                    b.HasKey("Id_Vagas");

                    b.ToTable("CadastroVagas");
                });

            modelBuilder.Entity("ProjetoFinal2.Models.CadastroVoluntario", b =>
                {
                    b.Property<int>("Id_Voluntario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CEP")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Atuacao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Voluntario");

                    b.HasIndex("Id_Atuacao");

                    b.ToTable("CadastroVoluntario");
                });

            modelBuilder.Entity("ProjetoFinal2.Models.CadastroVoluntario", b =>
                {
                    b.HasOne("ProjetoFinal2.Models.Atuacao", "Atuacao")
                        .WithMany("CadastroVoluntario")
                        .HasForeignKey("Id_Atuacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
